### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by shpitsmedia** [fshahinfar1/UnityLocalNotification#1]
Hello,

It seems that no sound is played when the notification is triggered.

Do you have an example showing how to add sound?

Thanks.

**Comment by fshahinfar1** [comment]
Hi @shpitsmedia 

This package currently leaves the notification sound configurations untouched meaning the
sound configuration is what user has set in his/her settings.

The point is `Unity3d` dev-team has done a great job developing a similar feature built in unity package it self.
I'll leave the [link](https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.0/manual/index.html) to its documentation page [here](https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.0/manual/index.html).
I guess unity dev-team will support their package
better than I, as a hobbyist, can do right now.

but if you still think adding the sound support feature is a good idea. please mention that in a comment. I will consider developing it.
